// Generated by https://quicktype.io

export interface CumplimientoResponse {
  data:          Seccion[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

// Generated by https://quicktype.io

export interface ProyectoCumplimientoResponse {
  data:          Seccion[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Seccion {
  idSeccion:    number;
  chSeccion:    string;
  nuProcentaje: number;
  auditorias:   Auditoria[];
}

export interface Auditoria {
  idAuditoriaCumplimiento:      number;
  idAuditoria:                  number;
  idProyecto:                   number;
  idDirector:                   number;
  mes:                          number;
  fecha:                        string;
  punto:                        string;
  idSeccion:                    number;
  cumplimiento:                 string;
  cumplimientoCalidad:          string;
  cumplimientoLegal:            string;
  documentoRef:                 string;
  aplica:                       boolean;
  motivo:                       string;
  tieneDocumento:               boolean;
  idDocumento:                  number;
  ultimoDocumentoValido:        boolean;
  cantidadDocumentos:           number;
  cantidadDocumentosValidados:  number;
}

export interface DocumentoResponse {
  data:          Documento;
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface DocumentosResponse {
  data:          Documento[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Documento {
  idDocumento:                      number;
  idAuditoriaCumplimientoProyecto:  number;
  motivo:                           string;
  fecha:                            string;
  documentoBase64:                  string;
  nombreDocumento:                  string;
  valido:                           boolean;
}

export interface TsProyectosResponse {
  data:          TSProyecto[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface TSProyecto {
  numProyecto:                  number;
  nombre:                       string;
  alcance:                      string;
  cp:                           string;
  ciudad:                       string;
  idEstatus:                    number;
  idSector:                     number;
  idTipoProyecto:               number;
  idResponsablePreconstruccion: number;
  idResponsableConstruccion:    number;
  idResponsableEhs:             number;
  idResponsableSupervisor:      number;
  idCliente:                    number;
  idEmpresa:                    number;
  idPais:                       number;
  idDirectorEjecutivo:          number;
  costoPromedioM2:              number;
  fechaIni:                     string;
  fechaFin:                     string;
}
