// Generated by https://quicktype.io

export interface UsuariosResponse {
    data:          Usuario[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface Usuario {
    idUsuario:    number;
    numEmpleado:  number;
    empleado:     string;
    activo:       boolean;
    ultimaSesion: string;
}

export interface PerfilesResponse {
    data:          Perfil[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface UsuarioPerfilesResponse {
    data:          UsuarioPerfil;
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface UsuarioPerfil {
    idUsuario: number;
    usuario:   string;
    perfiles:  Perfil[];
}

export interface Perfil {
    idPerfil:    number;
    perfil:      string;
    descripcion: null | string;
    activo:      boolean;
}

export interface ModulosResponse {
    data:          Modulo[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilModulosResponse {
    data:          PerfilModulo;
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilModulo {
    idPerfil:    number;
    perfil:      string;
    descripcion: null;
    modulos:     Modulo[];
}

export interface Modulo {
    idModulo:  number;
    modulo:    string;
    subModulo: string;
    tab?:      string;
    isTab:     boolean;
    activo:    boolean;
}

export interface PermisosResponse {
    data:          Permiso[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilPermisosResponse {
    data:          PerfilPermiso;
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilPermiso {
    idPerfil:    number;
    perfil:      string;
    descripcion: null;
    permisos:    Permiso[];
}

export interface Permiso {
    idPermiso: number;
    permiso:   string;
    activo:    boolean;
}

export interface ModulosArbolResponse {
    data:          ModuloArbol[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilModulosArbolResponse {
    data:          PerfilModuloArbol;
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface PerfilModuloArbol {
    idPerfil:    number;
    perfil:      string;
    descripcion: null;
    modulos:     ModuloArbol[];
}

export interface ModuloArbol {
    idModulo:   number;
    modulo:     string;
    activo:     boolean;
    submodulos: SubmoduloArbol[];
}

export interface SubmoduloArbol {
    idSubmodulo: number;
    subModulo:   string;
    activo:      boolean;
    tabs:        TabArbol[];
}

export interface TabArbol {
    idTab:  number;
    tab:    string;
    isTab:  boolean;
    activo: boolean;
}
