// Generated by https://quicktype.io

export interface EtapasPorProyectoResponse {
    data:          EtapasPorProyectoData;
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface EtapasPorProyectoData {
    numProyecto: number;
    fechaIni:    string;
    fechaFin:    string;
    etapas:      Etapa[];
}

export interface Etapa {
    idFase:    number;
    orden:     number;
    fase:      string;
    fechaIni:  string;
    fechaFin:  string;
    empleados: Empleado[];
}

export interface Empleado {
    id:              number;
    idFase:          number;
    numempleadoRrHh: number;
    empleado:        string;
    fechas:          Fecha[];
}

export interface Fecha {
    id:         number;
    mes:        number;
    anio:       number;
    porcentaje: number;
}
