// Generated by https://quicktype.io

export interface ObtenerClientesResponse {
    data:          Cliente[];
    success:       boolean;
    message:       null;
    transactionId: null;
}

export interface Cliente {
    idCliente: number;
    rfc:       string;
    cliente:   string;
    activo:    boolean;
}
