// Generated by https://quicktype.io

export type EstadosList = 'todos' | 'activos' | 'inactivos'

export interface PlantillasResponse {
  data:          Plantilla[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface PlantillaResponse {
  data:          Plantilla;
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Plantilla {
  idContratoTemplate: number;
  titulo:             string;
  template:           string;
  activo:             boolean;
}
